apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0007db
  labels: 
    volume-name: wpdb    
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: localhost
    path: /var/data/pv0007/db