apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0007files
  labels: 
    volume-name: wpfiles  
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: localhost
    path: /home/data/pv0007/files